region: eu-west-1
project: daidokoro

global:
  tags:
    - code: go
    - service: example
    - life: live

stacks:
  vpc:
    # stack policy - url or raw json can be specified here
    policy: https://s3-eu-west-1.amazonaws.com/daidokoro-dev/policies/stack.json

    cf:
      cidr: 10.11.0.0/16

  subnet:
    depends_on:
      - vpc
    cf:
      subnets:
        - private: 10.10.0.0/24
        - public: 10.10.2.0/24
