language: go

matrix:
  include:
    - go: 1.7.5
    - go: 1.8
    - go: tip

  allow_failures:
    - go: tip

before_install:
- eval export AWS_ACCESS_KEY_ID=\$${TRAVIS_BRANCH}_aws_access_key_id
- eval export AWS_SECRET_ACCESS_KEY=\$${TRAVIS_BRANCH}_aws_secret_access_key
- eval export AWS_REGION=\$${TRAVIS_BRANCH}_aws_region

install:
  - go get -t -v github.com/daidokoro/qaz

script: go test -v -cover
