language: go

matrix:
  include:
    - go: 1.7.5
    - go: 1.8
    - go: tip

  allow_failures:
    - go: tip

before_install:
- eval export AWS_ACCESS_KEY_ID=\$master_aws_access_key_id
- eval export AWS_SECRET_ACCESS_KEY=\$master_aws_secret_access_key
- eval export AWS_REGION=\$master_aws_region

install:
  - go get -t -v github.com/daidokoro/qaz

script: go test -v ./tests
