stages:
  - test
  - build

sudo: required
before_install:
  - eval export AWS_ACCESS_KEY_ID=\$master_aws_access_key_id
  - eval export AWS_SECRET_ACCESS_KEY=\$master_aws_secret_access_key
  - eval export AWS_REGION=\$master_aws_region

jobs:
  include:
    - stage: test
      language: go
      go: "1.12"
      script:
        - go test -v -short ./testing

    - stage: build
      language: go
      go: "1.12"
      if: tag =~ ^v
      script:
        - ./build.sh
        - ./publish-release.sh