
region: eu-west-1

project: encrypt

stacks:
  kmsLambda:
    source: https://raw.githubusercontent.com/daidokoro/qaz/master/examples/encryption/templates/kms-lambda.yml
    cf:
      code: https://raw.githubusercontent.com/daidokoro/qaz/master/examples/encryption/lambda.py

  custom:
    depends_on:
      - kms-lambda

    parameters:
      - Secret: password123
    cf:
      kms_kid: <your kms key id here>
      lambda_arn: "!ImportValue lambdaEncryptArn"
