{{- $tags := .global.tags -}}

AWSTemplateFormatVersion: '2010-09-09'
Resources:
{{- range $index, $value := .subnets.subnets }}
  {{- range $access, $cidr := $value }}

  {{ $access }}Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: eu-west-1{{ if eq $access `public` }}a{{ else }}b{{ end }}
      CidrBlock: {{ $cidr }}
      VpcId: !ImportValue "daidokoro-vpc-vpcid"
      Tags:
        - Key: Name
          Value: {{ $access }}subnet
    {{ range $i, $val := $tags }}
      {{- range $k, $v := $val }}
        - Key: {{$k}}
          Value: {{$v}}
      {{ end }}
    {{- end }}

  {{- end -}}
{{- end -}}
