# Global Values - [Required]
region: "eu-central-1"
project: "example-dev"

# Stack values
stacks:
  # Define sqs stack here
  sqs:
    source: https://raw.githubusercontent.com/daidokoro/qaz/master/examples/sqs/templates/sqs.yml
    cf:
      Queues:
        - QueueName: "daido"
        - QueueName: "koro"
      indexdocument: "main.html"
