Resources:
  LambdaEncryptRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole

      Path: "/"
      Policies:
      - PolicyName: LambdaEncryptPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            - kms:Encrypt
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: "*"

  EncryptFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: {{ GET .kmsLambda.code  | literal }}

      Description: Lambda Function to Encrypt Custom Resource Values
      FunctionName: cfnEncryptionFunction
      Handler: index.handle
      Role: !GetAtt LambdaEncryptRole.Arn
      Runtime: python2.7

Outputs:
  EncryptFunctionArn:
    Description: Encrypt Function ARN
    Value: !GetAtt EncryptFunction.Arn
    Export:
      Name: lambdaEncryptArn
